[project]
name = "ricksteves"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "h2>=4.2.0",
    "httpx>=0.28.1",
    "loguru>=0.7.3",
    "parsel>=1.10.0",
]
